# Generated by Django 5.2.4 on 2025-07-29 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.CreateModel(
            name='ArticleUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь статьи',
                'verbose_name_plural': 'Пользователи статей',
                'unique_together': {('article', 'user')},
            },
        ),
        migrations.AddField(
            model_name='article',
            name='users',
            field=models.ManyToManyField(help_text='Пользователи, связанные с этой статьёй', related_name='articles', through='article.ArticleUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
