# Generated by Django 5.2.4 on 2025-07-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_user_articleuser_article_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleuser',
            name='cleaned_text_for_llm',
            field=models.TextField(blank=True, help_text='Полный текст статьи, очищенный и подготовленный для анализа LLM. Может быть добавлен вручную.', null=True, verbose_name='Очищенный текст для LLM'),
        ),
        migrations.AddField(
            model_name='articleuser',
            name='is_manually_added_full_text',
            field=models.BooleanField(default=False, help_text='Указывает, был ли полный текст статьи добавлен пользователем вручную.', verbose_name='Полный текст добавлен вручную'),
        ),
        migrations.AddField(
            model_name='articleuser',
            name='structured_content',
            field=models.JSONField(blank=True, default=dict, help_text='Содержимое статьи, разбитое по секциям (например, abstract, introduction, methods, results, discussion, conclusion)', null=True, verbose_name='Структурированное содержимое'),
        ),
    ]
