# Generated by Django 5.2.4 on 2025-08-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_articleuser_cleaned_text_for_llm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleauthor',
            options={'verbose_name': 'Автор связанный со статьёй', 'verbose_name_plural': 'Авторы связанные со статьями'},
        ),
        migrations.AlterModelOptions(
            name='articleuser',
            options={'verbose_name': 'Статья связанная с пользователем', 'verbose_name_plural': 'Статьи связанные с пользователями'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='cleaned_text_for_llm',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_manually_added_full_text',
        ),
        migrations.RemoveField(
            model_name='article',
            name='structured_content',
        ),
        migrations.AddField(
            model_name='articleuser',
            name='primary_source_api',
            field=models.CharField(blank=True, help_text='API, из которого были взяты основные метаданные для этой записи (title, abstract).', max_length=100, null=True, verbose_name='API основного источника'),
        ),
    ]
